exports.blockchain = {
  None: 'none',
  Ethereum: 'ethereum',
  Polygon: 'polygon',
  Tezos: 'tezos',
  Avalanche: 'avalanche',
  Fantom: 'fantom',
  Binance_Smart_Chain: 'binance-smart-chain',
  Solana: 'solana',
  Arweave: 'arweave',
  Cardano: 'cardano',
  Flow: 'flow',
  Starknet: 'starknet',
  Juno: 'juno',
  Cosmos: 'cosmos',
  Hedera: 'hedera',
  Teal: 'teal',
};
