exports.category = {
  Nft: 'nft',
  Dao: 'dao',
  Art: 'art',
  Music: 'music',
  Collectibles: 'collectibles',
  Gaming: 'gaming',
  Defi: 'defi',
  Metaverse: 'metaverse',
  Trading_Cards: 'trading-cards',
  Infrastructure: 'infrastructure',
  Education: 'education',
  Startup: 'startup',
  Protocol: 'protocol',
  Investing: 'investing',
};
